### ISSUE TITLE
플레이어 상호작용에대하여

### ISSUE THREAD

**Issue by MetroJang** [haje-hwang/KimHwangJang#10]
플레이어가 움직이면서E를 누르면 플레이어가 멈추지않고 이동되어 변경된 위치에서도 상호작용되는 이슈가 있읍니다.
playercontrol.cs에서 수정 발암

**Comment by haje-hwang** [comment]
![image](https://user-images.githubusercontent.com/80046755/209086269-4439030c-4e8f-4be6-99d6-389b6fd0dcff.png)

![image](https://user-images.githubusercontent.com/80046755/209086760-7e382438-8eaf-415f-8fad-cb628101d34e.png)

moveVector.Equals(Vector3.zero)로 GameController에서 주는 moveVector가 zero면 즉시 멈추도록 했다.
김기범이 말하기를 tag를 ==로 비교하는 대신 CompareTag()를 사용하면
이 라인에 에러가 있을 때 에러 로그가 나오기 때문에 디버깅에 도움이 된다고 했다.
tag가 아닌 다른 오브젝트도 Equals()함수를 사용하면 좋을 것 같아서 사용했다.

![image](https://user-images.githubusercontent.com/80046755/209086688-b02baaf6-897e-4e37-91fb-be55816b2c53.png)
moveVector는 2번 사진(위의 사진)에서 보듯이 Input.GetAxis를 사용해서 키보드를 떼도 즉시 1에서 즉시 0이 되지 않고 사르르 0으로 바뀐다. 그러니까 움직이는 키에서 손을 떼도 즉시 멈추지는 않는다.
GetAxisRaw를 쓰면 되지만 개인적으로 바로 딱 멈추면 부자연스러운 느낌이 들어서 그냥 뒀다.
